### ISSUE TITLE
Encryption problems

### ISSUE THREAD

**Issue by swankmotor** [leafle/newman-reporter-teamcity#10]
Hello. Thanks for teamcity reporter. 
Have some encryption problems. Did you have any ideas, how to fix it?
![2017-10-02_10-23-11](https://user-images.githubusercontent.com/32448571/31067478-c13ef41a-a75b-11e7-9763-8f07ede2b4bc.png)
![2017-10-02_10-22-06](https://user-images.githubusercontent.com/32448571/31067477-c13c7258-a75b-11e7-9a27-1ac76426d9c8.png)

**Comment by leafle** [comment]
Looks like a bug related to escaping unicode characters for Teamcity. It's weird that Teamcity is interpreting the escape character as a normal character. Could you try downgrading to version 0.1.6?

**Comment by leafle** [comment]
@swankmotor, on a theory that the issue was that Teamcity requires unicode characters to be escaped with exactly 4 hex chars (`|0x0414` instead of `|0x414`), I made a change that does that. I'm not able to verify this since I don't have access to a Teamcity account at this point. If you can upgrade to version 0.1.10 and let me know if it fixes your issue, I'd greatly appreciate it. Thank you.
